### ISSUE TITLE
The text is not displayed on Debian 10 and LMDE 4.

### ISSUE THREAD

**Issue by kuzyaka62** [JonMagon/KDiskMark#59] opened 2021-10-19 08:52 UTC
Installed KDiskMark on Debian 10, Linux Mint Debian Edition 4 and on Debian 11.
Everything went fine on Debian 11
https://i.ibb.co/qnkmmg4/d11.png
and on Debian 10 and Linux Mint Debian Edition 4, a form without text was launched.
https://i.ibb.co/7YhZ0qq/d10.png
Is it treated somehow?

**Comment by JonMagon** [comment] 2021-10-19 09:19
Try running it from a terminal and see the output. I don't think the cause is in the application at all.

**Comment by kuzyaka62** [comment] 2021-10-20 15:17
If you run on LMDE 4 or Debian 10 KDiskMark-2.2.1-fio-3.27-x86_64.AppImage, then there are no problems with displaying the text.
However, there was another problem, KDiskMark-2.2.1-fio-3.27-x86_64.AppImage does not switch the interface language.
Is this how it should be?

**Comment by JonMagon** [comment] 2021-10-20 18:56
> If you run on LMDE 4 or Debian 10 KDiskMark-2.2.1-fio-3.27-x86_64.AppImage, then there are no problems with displaying the text. However, there was another problem, KDiskMark-2.2.1-fio-3.27-x86_64.AppImage does not switch the interface language. Is this how it should be?

It shouldn't be that way. I can confirm it, I did not notice before because of the installed package in the system. I need time to figure out what the cause is and fix it.

**Comment by JonMagon** [comment] 2021-10-30 20:32
> If you run on LMDE 4 or Debian 10 KDiskMark-2.2.1-fio-3.27-x86_64.AppImage, then there are no problems with displaying the text. However, there was another problem, KDiskMark-2.2.1-fio-3.27-x86_64.AppImage does not switch the interface language. Is this how it should be?

Fixed in https://github.com/JonMagon/KDiskMark/releases/download/2.2.1/KDiskMark-2.2.1-2-fio-3.27-x86_64.AppImage

**Closed by JonMagon** 2021-10-30 20:32 UTC
Labels: bug, unconfirmed
