### ISSUE TITLE
Cannot add folder /home/some_user

### ISSUE THREAD

**Issue by Semnodime** [JonMagon/KDiskMark#41] opened 2020-12-16 12:29 UTC
Installed via snap on LinuxMint 20
```
sudo snap install kdiskmark                 
sudo snap connect kdiskmark:mount-observe
sudo snap connect kdiskmark:hardware-observe
```

Apparently KDiskMark (or snap itself) is buggy or has no access, as the `select-folder-UI` greys out the `[open]-button`, once any empty folder is selected. This is the case for _all_ empty folders on my machine.

**Note:** All folders tested can be accessed by an unpriviledged user though.
![image](https://user-images.githubusercontent.com/19511852/102349502-b68f5d00-3fa3-11eb-9937-ad75ae3a84bf.png)

**Comment by JonMagon** [comment] 2020-12-16 14:40
Please check the revision number of installed kdiskmark: `snap info kdiskmark`

**Comment by Semnodime** [comment] 2020-12-18 05:19
Version: latest/stable 2.0.0 2020-12-14

**Comment by JonMagon** [comment] 2020-12-30 12:38
I don't know how to fix this. I tested also with Launchpad PPA and next release should work fine for Cinnamon. But I have no idea what's wrong with snap.
Try run kdiskmark with `env QT_QPA_PLATFORMTHEME= kdiskmark`

**Comment by JonMagon** [comment] 2021-01-25 19:32
As I understand it, the issue is related to Qt, fixed in https://github.com/qt/qtbase/commit/844967d297327dc72a1aa67644c1b2fa3fe6839c
Launchpad builds the snap with older Qt 5.9.5 while using `core18` .
In fact, I see no reason to use a native dialog, and https://github.com/JonMagon/KDiskMark/commit/04daeeabceb86ed4fca61fb1f1d12cfcaa9067b7 should resolve the issue.
I've just tested and it works well. The fixed version is currently available in the beta channel:
`sudo snap install kdiskmark --beta`

**Comment by JonMagon** [comment] 2021-01-28 10:02
2.1.1 is released on the latest/stable channel, fixed now.

**Closed by JonMagon** 2021-01-28 10:02 UTC
Labels: bug, confirmed, help wanted

**Comment by jaclas** [comment] 2021-01-30 15:26
I install 2.1.1 and I get this issue

**Comment by JonMagon** [comment] 2021-01-30 18:00
> I install 2.1.1 and I get this issue

I can't reproduce the issue anymore, you should open an issue using a template.
